legalName: "O=AcmeCorp Notary, L=London, C=GB"
devMode: true
image:
  tag: ""
secrets:
  existingSecret: corda-notary-secrets
certificates:
  existingSecret: corda-notary-certs
network:
  existingNetworkParams: corda-network-params
