devMode: true

db:
  type: h2

secrets:
  existingSecret: corda-notary-secrets

certificates:
  existingSecret: corda-notary-certs

network:
  existingNetworkParams: corda-network-params

persistence:
  storageClass: standard
  size: 10Gi

resources:
  requests:
    cpu: "500m"
    memory: 2Gi
  limits:
    memory: 2Gi

jvm:
  opts: "-Xmx1500m -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError"
